<?php

$translations = [
	"ALL_TABLES_ADD_SUBMIT"    	=> "Přidat",
    "PUBLICATION_ADD_HTMLTITLE" => "Přidat publikaci",
    "PUBLICATION_ADD_ISBN"      => "ISBN",
    "PUBLICATION_ADD_TITLE"     => "Název",
    "PUBLICATION_ADD_NUMPAGES"  => "Počet stran",
    "PUBLICATION_ADD_EDITION"   => "Vydání",
    "PUBLICATION_ADD_PUBLISHED" => "Datum publikace",
    "PUBLICATION_ADD_SUCCESS"   => "Publikace byla úspěšně přidána!",
    "PUBLICATION_SELECT_AUTHOR" => "Vyberte autora",
    "AUTHOR_ADD_HTMLTITLE" 		=> "Přidat autora",
    "AUTHOR_ADD_FIRSTNAME"		=> "Křestní jméno",
    "AUTHOR_ADD_LASTNAME"		=> "Příjmení",
    "AUTHOR_ADD_BORN"			=> "Datum narození",
    "AUTHOR_ADD_DECEASED"		=> "Datum úmrtí",
    "AUTHOR_ADD_NATIONALITY"	=> "Národnost",
    "AUTHOR_ADD_SUCCESS"   		=> "Autor byl úspěšně přidán!",
    "PUBLISHER_ADD_HTMLTITLE"	=> "Přidat nakladatelství",
    "PUBLISHER_ADD_SUCCESS"		=> "Nakladatelství bylo úspěšně přidáno",    
    "PUBLISHER_ADD_TITLE"		=> "Název",
    "PUBLISHER_ADD_ADDRESS"		=> "Adresa",
    "AGERANGE_ADD_HTMLTITLE"    => "Přidat věkovou skupinu",
    "AGERANGE_ADD_SUCCESS"      => "Věková skupina byla úspěšně přidána!",
    "AGERANGE_ADD_TITLE"        => "Název",
    "AGERANGE_ADD_FROM"         => "Od",
    "AGERANGE_ADD_TO"           => "Do",
    "GENRE_ADD_HTMLTITLE"       => "Přidat žánr",
    "GENRE_ADD_SUCCESS"         => "Žánr byl úspěšně přidán!",
    "GENRE_ADD_TITLE"           => "Název",
];