<?php

$translations = [
	"ALL_TABLES_ADD_SUBMIT"    	=> "Add",
    "PUBLICATION_ADD_HTMLTITLE" => "Add publication",
    "PUBLICATION_ADD_ISBN"      => "ISBN",
    "PUBLICATION_ADD_TITLE"     => "Title",
    "PUBLICATION_ADD_NUMPAGES"  => "Number of pages",
    "PUBLICATION_ADD_EDITION"   => "Edition",
    "PUBLICATION_ADD_PUBLISHED" => "Published date",    
    "PUBLICATION_ADD_SUCCESS"   => "Publication has been added successfully!",
    "PUBLICATION_SELECT_AUTHOR" => "Select author",
    "AUTHOR_ADD_HTMLTITLE" 		=> "Add author",
    "AUTHOR_ADD_FIRSTNAME"		=> "First name",
    "AUTHOR_ADD_LASTNAME"		=> "Last name",
    "AUTHOR_ADD_BORN"			=> "Born",
    "AUTHOR_ADD_DECEASED"		=> "Deceased",
    "AUTHOR_ADD_NATIONALITY"	=> "Nationality",
    "AUTHOR_ADD_SUCCESS"   		=> "Author has been added successfully!",
    "PUBLISHER_ADD_HTMLTITLE"	=> "Add publisher",
    "PUBLISHER_ADD_SUCCESS"		=> "Publisher has been added successfully!",    
    "PUBLISHER_ADD_TITLE"		=> "Name",
    "PUBLISHER_ADD_ADDRESS"		=> "Address",
    "AGERANGE_ADD_HTMLTITLE"	=> "Add agerange",
    "AGERANGE_ADD_SUCCESS"		=> "Age range has been added successfully!",
    "AGERANGE_ADD_TITLE"		=> "Name",
    "AGERANGE_ADD_FROM"			=> "From",
    "AGERANGE_ADD_TO"			=> "To",
    "GENRE_ADD_HTMLTITLE"		=> "Add genre",
    "GENRE_ADD_SUCCESS"			=> "Genre has been added successfully!",
    "GENRE_ADD_TITLE"			=> "Name",
];